### ISSUE TITLE
Timeline: ISO datetime format for data type

### ISSUE THREAD

**Issue by danieleguido** [humanitiesplusdesign/palladio#1]
Hi Palladio team,

First of all thank you very much for your remarkable work, I'm very proud of writing the very first public issue!
When modifying a Data Type format for a column, the list of possible datatypes lacks ISO datetime format: values like `2012-03-31T15:30:57` or `2012-03-31T15:30:57.123456Z` are not recognized as Date/Year, and the interface freeze.

Thanks in advance for your help.

**Comment by esjewett** [comment]
Hi Daniele,

ISO date support is undocumented, but it should actually work for the first example you give: ```2012-03-31T15:30:57``` It's likely that there is an unrelated bug in processing your data or with one of the new filters that is causing the problem. Apologies about that. Do you have a sample data set that triggers the problem that you can share? If you'd like to share it privately, feel free to email either the team or myself.

**Comment by danieleguido** [comment]
Thank you for your quick reply. Indeed, the dataset is a 1mb collection of tweets that show (at least) different datetime format. I guess that the ui freezing depends on the amount of errors to handle, since the data are loaded quickly and painlessly. 
Here are some lines that cause the error `values do not match this data type`:
```csv
id,url,user_id,user_screenname,timestamp,text,lang,coordinates,uniq_rt_hash,reply_to_user,reply_to_id
"319079516716793856","https://twitter.com/SAGEsociology/statuses/319079516716793856","SAGEsociology","SAGE Sociology","2013-04-02T15:30:59","Bruno Latour talks about 'modes of existence' in this podcast from Social Studies of Science http://ow.ly/jzQM1","en",,"ee08daa204517d4c235b751494fed8a5",,
"350026303895912449","http://twitter.com/doorsausage/statuses/350026303895912449","doorsausage",,"2013-07-01T17:11:05.245000","@AIMEproject there are many forms of truth, but do law and religion etc. also have their own forms of knowledge, not just truth?",,,"86771792162ad04cf48e37bd07206623",,
"350557526179315712","http://twitter.com/AIMEproject/statuses/350557526179315712","AIMEproject",,"2013-07-01T17:11:05.245000","@doorsausage It would be clearer to reserve knowledge for reference (REF), but if you use ''knowledge'' for other modes specify the mode REL",,,"460db59ca6911813dca642a6fda5ffff",,
"350557990170005505","http://twitter.com/AIMEproject/statuses/350557990170005505","AIMEproject",,"2013-07-01T17:11:05.244000","Le site français est maintenant accessible pour trois des quatre colonnes prévues. Nous en sommes très fiers Votre feedback serait précieux",,,"872b60356265c1aa49d8fd440f4283c1",,
"350558829064368128","http://twitter.com/AIMEproject/statuses/350558829064368128","AIMEproject",,"2013-07-01T17:11:05.244000","For those of you who read French, the site is now up and running for three out of its four columns offering a preview of the English site.",,,"563eac4942ab5759dc9bc8bed6b4491e",,
```

**Comment by esjewett** [comment]
Great - thanks. I will take a look at getting this working properly.

**Comment by esjewett** [comment]
This should be working now on the master branch. There is a separate issue with the timeline filter where it cuts off the last date in the dataset when operating at "day-level" granularity. I'll see about addressing that as well.

Could you try out the master branch and see if it is working for your full data set?

**Comment by esjewett** [comment]
Going to close this under the assumption that it's working. If not, please re-open.
