### ISSUE TITLE
Dowload from map view fails

### ISSUE THREAD

**Issue by cncoleman** [humanitiesplusdesign/palladio#106]
![screen shot 2015-11-06 at 10 27 05 am](https://cloud.githubusercontent.com/assets/288005/11005133/04af3cd8-8471-11e5-8fe6-08104cc7688a.png)

Using most recent (this morning ahr/data/architects tables. Download of PSave file fails from map view.

**Comment by cncoleman** [comment]
download fails from the Data Refine view as well.

**Comment by cncoleman** [comment]
Save file created in Safari works and load into Chrome.

**Comment by esjewett** [comment]
I'm having a hard time recreating. Can you send me the palladio save file from Safari so that I can see if I can recreate?

**Comment by cncoleman** [comment]
Me, too. Not sure what was going on there. The save file is in the ahr repo. But It works for me now in Chrome. False alarm.
