### ISSUE TITLE
save file from graph view does not save graph selections (1.1.3 in Chrome)

### ISSUE THREAD

**Issue by cncoleman** [humanitiesplusdesign/palladio#113]

**Comment by esjewett** [comment]
The Palladio save file? I'm not able to recreate the problem after selecting to use the sample data, selecting birthplace and gender in the graph view as well as a highlight and "size nodes", then saving a Palladio save file and reloading. Is there something more that triggers this?

**Comment by cncoleman** [comment]
I'll send you the file

**Comment by esjewett** [comment]
Thanks - if you can also let me know which dimensions were chosen, that would be good.
