### ISSUE TITLE
Loading a project from an URL does not initialize it correctly

### ISSUE THREAD

**Issue by jiemakel** [humanitiesplusdesign/palladio#117]
Loading a project from an URL (either via the GUI or via the file -parameter) results in the project being displayed in the data view and not the configured initial visualization view (in addition, the project title is not displayed).

Interestlingly, if you click on any *other* visualization view than the intended initial one, the initialization finishes, and actually brings up the initial view instead of the one you clicked on (still no project title though). All other views are also configured correctly when this happens. On the other hand, if you click on the intended visualization, you end up in a weird state where facets are correctly configured, but none of the views themselves are.

(Everything works fine when I just upload the project file from my own drive)

**Comment by esjewett** [comment]
Sorry for the delay - this should now be fixed on both the master branch and the main site in 1.1.4
