### ISSUE TITLE
Gallery view has usability issues

### ISSUE THREAD

**Issue by esjewett** [humanitiesplusdesign/palladio#12]
Doesn't really make sense to allow gallery dimensions to be chosen from more than one table.

**Comment by cncoleman** [comment]
Dimension selection window is confusing. There is no indication of which field you are selecting for.

**Comment by esjewett** [comment]
Good point. We should have a more descriptive header/description on the dimension selector modal, perhaps?






On Thu, May 7, 2015 at 3:39 PM -0700, "Nicole Coleman" <notifications@github.com> wrote:












Dimension selection window is confusing. There is no indication of which field you are selecting for.

**Comment by esjewett** [comment]
I've added a 'description' attribution to the 'modal' directive. If it is provided, it will replace the header text. I'll make use of that in the gallery view now.

**Comment by esjewett** [comment]
I've updated this on the master branch. If we want even more flexibility (maybe a title _and_ a secondary description, then it's fairly easy to add this functionality to the modal).

**Comment by esjewett** [comment]
Also addressed some brittleness when selecting dimensions that could result in errors on the console. Will close this issue.
