### ISSUE TITLE
A reviewed dimension should not have the "please review" tooltip

### ISSUE THREAD

**Issue by elizawe** [humanitiesplusdesign/palladio#124]
Even when the dot is grey, the tooltip says "please review"

**Comment by esjewett** [comment]
I'm not able to recreate, unfortunately. This is on the latest version on the website?

**Comment by elizawe** [comment]
![screen shot 2016-01-19 at 3 07 59 pm](https://cloud.githubusercontent.com/assets/13007109/12434872/74662136-bebe-11e5-9001-100608a491b6.png)

**Comment by esjewett** [comment]
I see. We actually shouldn't be displaying the grey dot at all in this scenario.

**Comment by esjewett** [comment]
Ok, I now recall that I actually don't remember if we are supposed to be showing the grey dot or not in this scenario. I've changed the tooltip text to "Verified" (see commit) and left it visible. This dot is visible only in the situation where the dimension has special characters but they have all been verified.
