### ISSUE TITLE
Data type mismatch gives two "dots" both gray and red. 

### ISSUE THREAD

**Issue by cncoleman** [humanitiesplusdesign/palladio#125]
<img width="331" alt="screen shot 2016-01-19 at 1 54 11 pm" src="https://cloud.githubusercontent.com/assets/288005/12433155/4c57ded2-beb4-11e5-906f-813dff610887.png">

If this is intentional, to indicate that there are some matches and some errors, we need a better method. When we add Breve Edit, this problem will be addressed.

**Comment by esjewett** [comment]
Is this on the sample data in Palladio version 1.1.4? I'm having trouble re-creating.

**Comment by cncoleman** [comment]
If you go into any sample data text dimension and change it to numeric, you should see it happen.

**Comment by esjewett** [comment]
Bingo. Thanks.
