### ISSUE TITLE
Gallery: Add interface suggestion that the Title be a unique value

### ISSUE THREAD

**Issue by elizawe** [humanitiesplusdesign/palladio#131]
![screen shot 2016-01-19 at 2 55 31 pm](https://cloud.githubusercontent.com/assets/13007109/12434627/b829f016-bebc-11e5-8ca2-71f3df354a69.png)

**Comment by esjewett** [comment]
Are we thinking just updating the title of the dimension selector? I'll push that, but please re-open if you had something else in mind.

<img width="265" alt="screen shot 2016-02-24 at 9 01 53 am" src="https://cloud.githubusercontent.com/assets/4822/13289337/4d3ecc56-dad5-11e5-9fa3-a7930fcbfd27.png">
