### ISSUE TITLE
Facet filter on attributes in secondary table

### ISSUE THREAD

**Issue by mdlincoln** [humanitiesplusdesign/palladio#136]
I've both a primary table of objects, as well as a secondary table with a coordinate column as well as a few other attributes (i.e. `place_type`). After creating a map, graph, table, or gallery, I pull up the Facet toolbar and add a facet based on one of the attributes in the secondary table. The facet list shows up correctly (all the counts for `place_type` are correct), however clicking on one of those values to filter the view doesn't seem to work. Does facet filtering currently only work based on attributes in the primary table?

**Comment by esjewett** [comment]
Sorry for the delay responding. It should work on attributes in secondary tables as well. Do you see any errors on you Javascript console? Or can you share a Palladio save file where this issue occurs? Thanks!

**Comment by mdlincoln** [comment]
For the life of me, I cannot manage to replicate this problem with the same data. Sorry for the false alarm!

**Comment by esjewett** [comment]
There is some brittleness in Palladio code that can be triggered by switching back and forth between the data and visualization views, or by adding and removing filter visualizations. You might have hit one of these bugs. If this happens in the future, take a look at the Javascript console and take a quick screenshot of the first errors that appear. Will help us get to the bottom of it, and possibly help to recreate the problem :)

**Comment by mdlincoln** [comment]
Noted - FWIW I was working on some data with several thousand rows, and so
Palladio was running a bit slowly to begin with. I will keep an eye out for
the bug again.

On Fri, Feb 5, 2016 at 9:43 AM, Ethan Jewett <notifications@github.com>
wrote:

> There is some brittleness in Palladio code that can be triggered by
> switching back and forth between the data and visualization views, or by
> adding and removing filter visualizations. You might have hit one of these
> bugs. If this happens in the future, take a look at the Javascript console
> and take a quick screenshot of the first errors that appear. Will help us
> get to the bottom of it, and possibly help to recreate the problem :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/humanitiesplusdesign/palladio/issues/136#issuecomment-180384306>
> .
>



-- 
Matthew D. Lincoln
Ph.D Candidate
Department of Art History & Archaeology <http://arthistory.umd.edu>
University of Maryland
College Park, MD 20742

mlincol1@umd.edu
matthewlincoln.net
