### ISSUE TITLE
Timeline - add option to group by none

### ISSUE THREAD

**Issue by cncoleman** [humanitiesplusdesign/palladio#137]

**Comment by esjewett** [comment]
If you try the latest, there is an "X" next to the group-by selection that allows the user to clear the selection.

<img width="400" alt="screen shot 2016-02-05 at 10 35 59 am" src="https://cloud.githubusercontent.com/assets/4822/12852381/5464c322-cbf4-11e5-9b07-cc14c25050fc.png">

Look ok?

**Comment by cncoleman** [comment]
Does it not work to just have "none" as an option in the drop-down list?

**Comment by esjewett** [comment]
It's a dimension selection modal, not a drop-down, so it's not obvious but you are already allowed to actually click the selected dimension again to de-select it. That leaves no dimension selected. Previously this would break the timeline, but now it works as well.

I'd not want to add another "None" option in the modal, as it would look like a dimension. We could add a control to the modal to deselect all dimensions or something like that.
