### ISSUE TITLE
1.2  Facet filter column alignment problem

### ISSUE THREAD

**Issue by cncoleman** [humanitiesplusdesign/palladio#149]
The last dimension added drops down below the others. 
![screen shot 2016-07-05 at 2 30 53 pm](https://cloud.githubusercontent.com/assets/288005/16600998/dfdb764e-42be-11e6-8d33-a98f4830f7d8.png)
![screen shot 2016-07-05 at 2 31 16 pm](https://cloud.githubusercontent.com/assets/288005/16601002/e54f29cc-42be-11e6-8e86-aca6f27f13c1.png)

**Comment by esjewett** [comment]
Yes, have seen this before. I think it happens in Safari but not Chrome, right? I will plan to fix.

**Comment by esjewett** [comment]
Fixed in 1.2.1 via a fix in palladio-facet-filter
