### ISSUE TITLE
Timespan Displays Deathdate as same as birthdate if one or the other is missing.

### ISSUE THREAD

**Issue by cncoleman** [humanitiesplusdesign/palladio#160]
This is a distortion of the data and results in a misrepresentation of the data in the graph. See attached.
![screen shot 2016-08-16 at 2 05 08 pm](https://cloud.githubusercontent.com/assets/288005/17716451/965d3884-63bd-11e6-8453-22d528b9bc42.png)

**Comment by esjewett** [comment]
Possibly 2 separate issues here:

1. The tooltip display that should (I agree) show which one is missing
2. The visual display that displays either a vertical line or a single dot, depending on the view being shown.

In the case of 1, I completely agree that we should indicate the missing value in the tooltip. In the case of 2, what are your thoughts on what we should be doing differently here?

**Comment by cncoleman** [comment]
If we are capturing and processing the data as 1. viable value  + 2. missing value, then we would be fine with the graphic. It's not actually the graphic display that is the problem. It's the resulting interaction/data manipulation. I cannot filter to just people whose birthdate falls in a certain range. If those people are  missing a death date, the death date becomes equal to the birthdate. As a result, I have to select the range of date in both the birthdate and the deathdate. That is illogical and interferes with filtering on complete birth-death dates.

**Comment by cncoleman** [comment]
Attached an image showing how filtering on Birth year yields an incorrect result. 
![screen shot 2016-08-16 at 2 50 08 pm](https://cloud.githubusercontent.com/assets/288005/17717123/ed7616ec-63c0-11e6-9577-1d577d28cf52.png)

**Comment by cncoleman** [comment]
I guess we could treat it as a feature instead of a bug. The advantage is that it gives you a way to select those who do not have birthdates. But the interaction is too wrong. It just doesn't make sense.

**Comment by esjewett** [comment]
Ahhhhh, yup. Thanks, I think that clarifies what I need to do here. Will see what I can do.

**Comment by esjewett** [comment]
This should be fixed in palladio-timespan-component version 1.1.0. If you pull down the latest master branch of palladio-app, it should be fixed there too (you'll need to do a 'bower update'). It's tagged as palladio-app#1.2.2 and we can push it to the main site once we are ready.

Can you confirm if it works?

**Comment by cncoleman** [comment]
It works! Thanks


________________________________

**Comment by esjewett** [comment]
Cool. Just as a quick overview, everything excep the tool tips should be the same in "bars" mode. But in the parallel/slope-graph mode it no longer displays lines for things that are missing one of their dates. Instead, I have started showing the endpoint dots in this mode on the axes. So for data points with one one of the dates it just shows a dot on the appropriate axis. 
Thanks,Ethan






On Tue, Aug 16, 2016 at 6:19 PM -0500, "Nicole Coleman" <notifications@github.com> wrote:










It works! Thanks





________________________________

**Comment by cncoleman** [comment]
That's a good solution. Nice.





On Tue, Aug 16, 2016 at 5:38 PM -0700, "Ethan Jewett" <notifications@github.com<mailto:notifications@github.com>> wrote:

Cool. Just as a quick overview, everything excep the tool tips should be the same in "bars" mode. But in the parallel/slope-graph mode it no longer displays lines for things that are missing one of their dates. Instead, I have started showing the endpoint dots in this mode on the axes. So for data points with one one of the dates it just shows a dot on the appropriate axis.
Thanks,Ethan






On Tue, Aug 16, 2016 at 6:19 PM -0500, "Nicole Coleman" <notifications@github.com> wrote:










It works! Thanks





________________________________
