### ISSUE TITLE
Data layer in Map view is reverse of the intuitive "top" of the stack. 

### ISSUE THREAD

**Issue by cncoleman** [humanitiesplusdesign/palladio#161]
Example: Blue is on top in the layers settings window, but on the bottom in the map view.

![screen shot 2016-08-16 at 2 57 45 pm](https://cloud.githubusercontent.com/assets/288005/17717291/0e01fc7c-63c2-11e6-8275-960c8d3d954d.png)

**Comment by esjewett** [comment]
This should be fixed in the palladio-map-component version 1.1.1. I've updated palladio-app dependencies so that palladio-app#1.2.3 uses this version of the map component. If you pull the latest and 'bower update', you should see the order of the data layers reversed to be more intuitive.
