### ISSUE TITLE
Order columns in Table Brick

### ISSUE THREAD

**Issue by cncoleman** [humanitiesplusdesign/palladio#162]
The table columns in the component do not match the order when the table is created and the order also does not match the list in the app script. It would be helpful to be able to determine the sequence of columns.

**Comment by esjewett** [comment]
I've taken a couple of shots at this and haven't been able to quite get it yet. Will try again, at least for the components/bricks case, we should be able to do this.

**Comment by esjewett** [comment]
This should be fixed (for components at least) in palladio-table-component#1.1.1
