### ISSUE TITLE
Timeline filter scale should remain static

### ISSUE THREAD

**Issue by cncoleman** [humanitiesplusdesign/palladio#163]
In order to compare the distribution of data in the histogram, it would help if the scale could remain static based on the full data set. For Voltaire's letters, grouped by nationality, if I filter to a subset, the y axis scale shifts on the timeline. This is confusing because it is essentially regenerating an entirely new graphic representation instead of allowing me to compare the subset to the total.

**Comment by esjewett** [comment]
Good point. Should be able to do that, but the map updates took longer than I expected and I've got to turn in for the night. Will try to do this tomorrow morning first thing.

**Comment by esjewett** [comment]
This should be fixed in palladio-timeline-component#1.0.3 if you start using that.
