### ISSUE TITLE
Palladio Embed discrepancy with set parameters

### ISSUE THREAD

**Issue by cncoleman** [humanitiesplusdesign/palladio#164]
![screen shot 2016-08-25 at 1 23 48 pm](https://cloud.githubusercontent.com/assets/288005/17984750/77f99138-6ac7-11e6-9def-c34981300207.png)

You can see (faintly) behind the code window that the timeline displayed in the embed app has a group applied. It is "gender". And yet in the code, the group for timeline is "null". When viewing this component embedded in an html page, a group again appears in the timeline. It seems to be "Additional Language".

**Comment by esjewett** [comment]
I hope this is fixed. There was a bug in the palladio-timeline-component (https://github.com/humanitiesplusdesign/palladio-timeline-component/issues/2), the palladio-embed-app was using an old version of the component, and the embed app was generating the wrong embed code in this scenario.
