### ISSUE TITLE
embed app not recognizing facet dimensions

### ISSUE THREAD

**Issue by cncoleman** [humanitiesplusdesign/palladio#165]
![screen shot 2016-08-29 at 10 41 32 am](https://cloud.githubusercontent.com/assets/288005/18060902/555aa584-6dd5-11e6-860d-ed294a6866f4.png)

Note that the embed app gives the notice that dimensions are not configured for facet. Yet the code does show dimensions configured for facet. Among them is the odd "0.nm4o3xw14liqt0n0og3qh0k9"

**Comment by esjewett** [comment]
IIRC, there's a particular scenario in which this occurs when an invalid dimension key is somehow included in the save file for the facet filter. Which save file is this? I will take a look.

**Comment by cncoleman** [comment]
The missing dimension is lat lon exists. File is Voltaire Network Letters.palladio.1.2.1.json in the repo republicofletters

**Comment by esjewett** [comment]
Ok, looks like the save file itself is corrupt and doesn't include the proper dimension key :-/ Will try to fix, but it's probably going to involve either creating another save file after I fix Palladio or manually changing the existing one in place. Would you like me to change the current one in place?

**Comment by cncoleman** [comment]
sure. a fix on the current file would be the most effiencient. thanks

**Comment by esjewett** [comment]
Sorry I didn't update. Unfortunately I've looked further and this is a problem with the way we save and load these files, so I don't think it will be possible to just do a fix for the file in place. Working on it though...

**Comment by esjewett** [comment]
I've updated the palladio-embed-app to pull the latest version of Palladio, which fixes these issues in the save file and load process if you run it locally. I will also update that Palladio version in palladio-app and work to push this to the live site along with other fixes included in the 1.2.2 milestone.

You'll also see a commit coming to the republicofletters repo that will fix that load file in-place (if you use the new palladio-embed-app).

**Comment by cncoleman** [comment]
Super. Let me know when it's live!

**Comment by esjewett** [comment]
Just pushed to republicofletters, so that should work in the embed app now. You need to update the bower palladio dependency of all your applications to 1.2.2.

**Comment by esjewett** [comment]
Now live on the hdlab Palladio site as well, so new save files generated from here should just work.

**Comment by cncoleman** [comment]
Do we need to update the dependencies again in the embed app?

**Comment by esjewett** [comment]
Shouldn't be necessary unless you are running into the date issues that were fixed in palladio 1.2.3 (#159)
