### ISSUE TITLE
Links to PDFs on the tutorial/FAQ page are broken

### ISSUE THREAD

**Issue by esjewett** [humanitiesplusdesign/palladio#169]
Page at http://hdlab.stanford.edu/palladio/help/ links to http://hdlab.stanford.edu/palladio/doc/scenario-simple-map.pdf but should be http://hdlab.stanford.edu/doc/scenario-simple-map.pdf (same for point-to-point tutorial).

**Comment by jsuttonmorse** [comment]
In faq.md these point to - `({{ site.baseurl }}/doc/scenario-simple-map.pdf)`
(site.baseurl is '/palladio' )

Updated the links in faq.md (there are three) on the documentation-updates branch.
