### ISSUE TITLE
Loading a remote linked save file doesn't seem to work

### ISSUE THREAD

**Issue by esjewett** [humanitiesplusdesign/palladio#171]
https://stacks.stanford.edu/file/druid:jt797ft9555/VoltaireCorrespondenceNetwork-people.palladio.1.2.3.json

Loading just results in a never-ending spinner.

**Comment by cncoleman** [comment]
When I try to load data from link in Palladio 1.2.4 using https://stacks.stanford.edu/file/druid:jt797ft9555/VoltaireCorrespondenceNetwork-people.palladio.1.2.3.json
It just spins.

**Comment by cncoleman** [comment]
Wait! after about 5 minutes it did finally load in the app

**Comment by esjewett** [comment]
Really? :-/ It should *not* take 5 minutes. Need to look into it.

**Comment by cncoleman** [comment]
It loads fine into the jekyll site for the components. It doesn't seem to load well in the live Palladio app.
