### ISSUE TITLE
Tutorial on how to submit an update to the documentation

### ISSUE THREAD

**Issue by esjewett** [humanitiesplusdesign/palladio#180]
I think we should encourage people to submit pull requests to update the documentation. Especially for the "Testimonials" page, I would like to encourage people to submit pull requests if they have done something cool with Palladio and published it or written about it. The steps are:

 1. Fork the repository
 2. Make a change to the gh-pages branch (probably will need some guidance on where to make changes here)
 3. Create a pull request against the gh-pages branch of the original palladio repository

@jsuttonmorse would you be up for putting this together and adding it to the tutorials?

**Comment by jsuttonmorse** [comment]
Updated & checked in.
