### ISSUE TITLE
Map visualization "Map layers" div 

### ISSUE THREAD

**Issue by valentinarachiele** [humanitiesplusdesign/palladio#183]
When you're in the "Map" visualization menu, the "Map layers" div doesn't show a vertical scroll bar, so you're not able to reach the bottom part and clicking the "Add layer" button.

**Comment by esjewett** [comment]
This is also https://github.com/humanitiesplusdesign/palladio-map-component/issues/2 (But fine to post it here.)

I will try to fix today - sorry we haven't gotten to it previously.

**Comment by esjewett** [comment]
There is an imperfect but hopefully decent fix in place that should let you scroll the settings panel on the map so you can get down to the "Add layer" button no matter your screen size.

**Comment by valentinarachiele** [comment]
Yes, it definitely works. Thank you!
