### ISSUE TITLE
Facet filter dimension selection not working

### ISSUE THREAD

**Issue by cncoleman** [humanitiesplusdesign/palladio#19]
I could only load one dimension.

**Comment by esjewett** [comment]
I see the issue - seems related to re-introducing the "pill" look for some reason. I'll investigate and fix.

**Comment by esjewett** [comment]
It wasn't related to @giorgiocaviglia's changes. I'm not sure what caused it to pop up suddenly. In any case, it should be fixed on the master branch now, and in general there is a more robust method of dynamically calculating how much room the facets need in place now. I'm going to close this, but if it is still broken for any reason, please re-open.
