### ISSUE TITLE
Frequently find facet buttons not working

### ISSUE THREAD

**Issue by Xuyuan71** [humanitiesplusdesign/palladio#192]
I upload my data and want to graph it, showing "Title" linked to "Term list"

I frequently find that the "facets" don't respond when I set them.  For example, I would like to view the "Genre2" facet, and filter to "Shangqing" in this set.  Although I can view the list of Genre2 facets, the facet buttons themselves are unresponsive, not filtering to the selected facet. Also the button to download the .json will not respond either.

What to do?
[Daoist.Canon.20.Drugnames.txt](https://github.com/humanitiesplusdesign/palladio/files/4037697/Daoist.Canon.20.Drugnames.txt)

**Comment by esjewett** [comment]
@Xuyuan71 Could you let me know what browser you are using and maybe share a short screen capture of what you are seeing? I  *think* it's working for me, but if there is an issue in a different browser I'd like to recreate the problem. If you @ me, I'll get an email about your issue and respond more quickly.

**Comment by Xuyuan71** [comment]
@esjewett Thanks.  I use Chrome on a MacBook Pro.  

Well, I'm not sure what happened, but uploading today, it now works.  So was able to download this .json file, which should show the facets working. Not sure what changed, but thanks!

https://www.dropbox.com/s/dapr53g65jrjt0h/Data%20export.palladio.1.2.9.json?dl=0
