### ISSUE TITLE
Updating data

### ISSUE THREAD

**Issue by cncoleman** [humanitiesplusdesign/palladio#30]
When a previously viewed data set is updated (a table deleted, modified offline, re-attached to primary table) is does not appear in visualization interface and no error is thrown.

**Comment by esjewett** [comment]
This is for an extension table? I just recreated this error with the Places table in the sample. Actually not even necessary to view it first - if you delete it and re-upload it in the refine stage, the places won't be available in the map view. Will fix.

**Comment by esjewett** [comment]
Closing as part of #39 - I believe this is the same problem?
