### ISSUE TITLE
cannot load SPARQL table

### ISSUE THREAD

**Issue by mdlincoln** [humanitiesplusdesign/palladio#31]
While I am able to retrieve data from a SPARQL endpoint through the Palladio interface, it does not give me the option to then load the table. For example, using the British Museum endpoint `http://collection.britishmuseum.org/sparql.json`:

```
SELECT ?type (COUNT(?type) as ?n)
WHERE {
  ?object bmo:PX_object_type ?object_type .
  ?object_type skos:prefLabel ?type .

  ?object ecrm:P108i_was_produced_by ?production .
  ?production ecrm:P9_consists_of ?date_node .
  ?date_node ecrm:P4_has_time-span ?timespan .
  ?timespan ecrm:P82a_begin_of_the_begin ?date .
  FILTER(?date >= "1580-01-01"^^xsd:date && ?date <= "1600-01-01"^^xsd:date)
}
GROUP BY ?type
ORDER BY DESC(?n)
```

I can preview the results successfully:

![screen shot 2015-07-12 at 6 07 05 pm](https://cloud.githubusercontent.com/assets/4392604/8640294/da2cd62a-28c0-11e5-8157-e8d578ac00cf.png)

However the "Load data" button remains inactive:

![screen shot 2015-07-12 at 6 07 11 pm](https://cloud.githubusercontent.com/assets/4392604/8640295/e8ef6060-28c0-11e5-8701-a483b535f2d6.png)

**Comment by esjewett** [comment]
Indeed. Thanks for the report! Will get this fixed ASAP - hopefully today.

**Comment by esjewett** [comment]
So, usually Palladio expects SPARQL results in CSV/TSV format. It looks like the British Museum endpoint supports only JSON and XML formats. Is that accurate? Assuming this is the issue, and that it would generally be nice to support JSON result formats, I'm going to have Palladio naively convert the JSON format into a CSV format in the event that the return value is JSON and not a string.

**Comment by esjewett** [comment]
I've bumped the version on http://palladio.designhumanities.org/ to 1.0.1 and loading from this endpoint (or any SPARQL endpoint) in JSON format should now work. Thanks again for reporting the issue. I'm going to close this one. Please go ahead and open a new issue if you run into any other SPARQL issues. It is not a very heavily used part of the application as far as we are aware, so we appreciate you delving into it.

**Comment by mdlincoln** [comment]
Thanks for following up so quickly on this! I've a few colleagues using this with some different SPARQL endpoints (none of which offer CSV/TSV download!) so I'll report back if we encounter further difficulties.
