### ISSUE TITLE
Allow an "ignore" option for special characters in data

### ISSUE THREAD

**Issue by cncoleman** [humanitiesplusdesign/palladio#38]
When special characters are valid, we should be able to "ignore" and the red dot should change to a check mark to indicate that the issue has been checked and ignored

**Comment by esjewett** [comment]
Based on discussion: Add an "ignore all" link below the list of special characters. If a special character (say "-") is selected, then change to "ignore '-'".

Question: How to display the character when it is ignored?

**Comment by cncoleman** [comment]
Actually, "ignore" is ambiguous. We used to have "ignore" with an open field to type in any value/string to ignore in the data set. This is different. We want to indicate "Verified". 
Steps:
1. Edit dimension that indicates a problem (red dot).
2. Designate a special char for "multiple values delim"
or
3. Click on the special character to filter on those values
If no other action is taken, "Verified" appears in green below the Multiple Values Delimiter box and the Data view shows a green empty circle in place of the red solid circle.

To un-verify:
Click on the special character again. It goes back to light gray background instead of dark gray.
The Data view shows an empty red circle (reviewed, but not changed) instead of the solid circle (problem not reviewed)

![image](https://cloud.githubusercontent.com/assets/288005/9916960/fc0bb7ac-5c73-11e5-9787-118698d50582.png)


For the data page, the Fontawesome icon should be Icon-circle-blank but adding that class does not appear in Chrome deve. Maybe we have an outdated version of Fontawesome.
http://fortawesome.github.io/Font-Awesome/3.2.1/icon/circle-blank/

**Comment by cncoleman** [comment]
The above is not a solution. The action (clicking the special character) is ambiguous because it already has the function of filtering. Also, the solution does not work for more than one special character. 

Instead, the goal is to notify the user that the dimension has been checked. We do not offer feedback that any dimension has been visited (like a visited link). We'll leave that alone and focus on allowing the researcher to verify that the special character status is alright. We assume two scenarios: 1. The special character(s) have been checked and the researcher has not made a decision about what to do; 2. The special character(s) have been checked and a decision was made about how to handle them.

**Comment by cncoleman** [comment]
In the edit dimension window, filtering on a special character and verifying it are the same action. Since that is currently the only thing we flag for review, reviewing it is enough to change the Close button to checkmark Done. 
The "review" dot on the data list page for that dimension changes from red to gray.

![specialchars](https://cloud.githubusercontent.com/assets/288005/10144348/135ee322-65d2-11e5-9aa2-f64236d09c7a.png)

![specialchars002](https://cloud.githubusercontent.com/assets/288005/10144355/182ea464-65d2-11e5-9859-cccf31b48478.png)

**Comment by cncoleman** [comment]
The additional explanatory text has been removed. The Help (?) dialog should explain the purpose.

**Comment by esjewett** [comment]
Looks good. I think this will work. I'll assign back to myself and will try to get to it tomorrow morning.

**Comment by esjewett** [comment]
Notes for myself: Click on each special character to verify it. (Maybe use a red shadow to indicate which characters are not verified.)
