### ISSUE TITLE
Deleting a table (and adding another 

### ISSUE THREAD

**Issue by cncoleman** [humanitiesplusdesign/palladio#39]

**Comment by cncoleman** [comment]
Deleted Places, modified the data outside of Palladio and re-loaded. New data table will not "extend" and is not available to views. A complete re-install of tables seems to be the only solution.

**Comment by esjewett** [comment]
Ok, I can recreate this. I'm sure I've tried before and been unable to figure out how. Pretty good idea what the problem is.

**Comment by esjewett** [comment]
I believe now fixed on master.

**Comment by cncoleman** [comment]
Great. I'll test it.
