### ISSUE TITLE
Add Mapbox branding when using Mapbox tiles

### ISSUE THREAD

**Issue by esjewett** [humanitiesplusdesign/palladio#51]
Need to look into this, but we should obviously abide by their attribution policy.

**Comment by cncoleman** [comment]
https://www.mapbox.com/help/attribution/

**Comment by esjewett** [comment]
This should be fixed on master. I think we had these in at one point but they were removed for some reason. I believe that the new layers use both MB and OSM features, so we should have both notices. I'm also leaving in the Leaflet prefix, which I don't believe is required, so we can remove it if that is preferable.
