### ISSUE TITLE
Make it possible to define a bounding box for the component map

### ISSUE THREAD

**Issue by cncoleman** [humanitiesplusdesign/palladio#53]
There are good use cases for a fixed map that displays data, but is not zoomable. This would make the components a bit closer to illustrations.

**Comment by esjewett** [comment]
Related to #40. Should be able to tackle both at the same time. This particular setting would probably best be an option added to the component map, along with an option to set the center point and zoom level.

**Comment by esjewett** [comment]
This exposes an API for setting center and zoom level. We can do bounds if we want as well, but the functionality is more or less equivalent and possibly more accessible. In the component context:

```
map.getOptions().centerCoordinates([50, 0]);
map.getOptions().zoomLevel(6);
```
