### ISSUE TITLE
show ([number selected out of] / [total number]) for each dimension

### ISSUE THREAD

**Issue by cncoleman** [humanitiesplusdesign/palladio#57]
show ([number selected out of] / [total number]) for each dimension.

We need to let people know at a glance how many of a thing they are seeing in a view. We can do this easily with FF instead of mucking up the interface with more information.

**Comment by esjewett** [comment]
So, we need changes to Crossfilter to track unfiltered values ([total number]) correctly. The way we used to do this in the facet filter (and the way we currently do this in the map view for the purposes of the legend calculation) is a bad hack and depends on a custom build of Crossfilter we maintain.

Now that https://github.com/crossfilter/crossfilter exists (a community fork), I would like to incorporate support for these types of calculations into core Crossfilter and the Reductio library. I'll propose adding the necessary capabilities to my collaborators on the Crossfilter fork and see what we can do.

**Comment by cncoleman** [comment]
Super. If that's not possible, we'll need to count the nodes in the view and display that somehow.

**Comment by esjewett** [comment]
This should be working now. After the groundwork of adding the necessary functionality to Crossfilter and Reductio, it was just a very small change in Palladio. Should make it much easier to do this in many places (the timeline, vis a vis Mapping the Republic of Letters, for instance).
