### ISSUE TITLE
Allow use of WMS URLS

### ISSUE THREAD

**Issue by cncoleman** [humanitiesplusdesign/palladio#61]

**Comment by esjewett** [comment]
This is now supported. Try with example URL: http://mesonet.agron.iastate.edu/cgi-bin/wms/nexrad/n0r.cgi and Layer: nexrad-n0r-900913  (used in example at https://www.mapbox.com/mapbox.js/api/v2.2.2/l-tilelayer-wms/)

One change: Now when the custom tileset option is selected, the images of the different tilesets collapse to leave room for the custom tileset options.

**Comment by cncoleman** [comment]
We want to be able to use Earthworks resources via WMS (particularly since JAck Reed recommended that we support WMS). But they have not as yet revealed the necessary WMS services through Earthworks. Jack said it is coming next week at our request. We are invited to follow and comment on the issue here: https://github.com/geoblacklight/geoblacklight/issues/348
