### ISSUE TITLE
In timespan tooltip, provide the group name

### ISSUE THREAD

**Issue by esjewett** [humanitiesplusdesign/palladio#62]

**Comment by esjewett** [comment]
Also re-enabling grouped-bars layout.

**Comment by esjewett** [comment]
@cncoleman Can you check out the latest after this commit? The timespan filter now allows the user to select the layout they want to see again, and we (re)introduce grouped-bar layout. However, the introduction of the layout selector takes up more vertical space, so I expanded the chart to take up the space as well.

**Comment by cncoleman** [comment]
I think it looks great. We are always going to have a problem with the filters taking up too much screen real estate. That's one reason the "Palladio Building Blocks" component system will be so welcome: no configuration windows in the way and no filters obscuring the primary view.

**Comment by cncoleman** [comment]
What ever happened to the minimized timeline view? I don't remember why we let that go. Even for the timespan view, to have the ability to get it out of the way, while still being able to brush would be very useful.

**Comment by esjewett** [comment]
Great - glad you think it looks good.

The minimized timeline was lost when we converted from the double timeline to the single timeline. The minimized timeline was just the "mini" timeline moved up to the top. We should bring back that functionality. Will create an issue.

**Comment by cncoleman** [comment]
What is the purpose of Group by in the bars layout (vs the grouped bars layout)? Maybe remove that option from the Bars only?

**Comment by esjewett** [comment]
It's still used in the detail of the tooltip. I can remove it, or I could change the label of the field to "Detail" or something like that if the "Grouped Bars" layout isn't chosen. What do you think?

**Comment by cncoleman** [comment]
Lets leave it. it's logical once you realize that its in the tooltip.The items still have a group to apply even if the layout does not reveal it.

**Comment by esjewett** [comment]
Sounds good. We can revisit if it proves confusing.
