### ISSUE TITLE
Wha? Legend malfunction.

### ISSUE THREAD

**Issue by cncoleman** [humanitiesplusdesign/palladio#64]
https://www.dropbox.com/s/a7nke19hdcud6bh/Screenshot%202015-09-24%2016.02.38.png?dl=0

**Comment by esjewett** [comment]
Is there a layer defined on the map here? Bug either way, but just want to be able to recreate quickly when I go in to fix it.

**Comment by esjewett** [comment]
I believe this is now fixed along with #26. Both caused by the same change I made some time ago as part of performance improvements in the map view. This particular change was actually not central to the performance improvement (still works with Voltaire data, for example), so I've changed it back.
