### ISSUE TITLE
Look into Map performance in alpha.03

### ISSUE THREAD

**Issue by esjewett** [humanitiesplusdesign/palladio#73]
Seems to be slower....

May also want to display a "processing" indicator of some sort.

**Comment by esjewett** [comment]
2 performance issues that need to be addressed:

 1. The use of aliasProp function from Reductio - we need to replace with alias instead.
 2. (the bigger issue) - use of valueList function of Reductio results in huge results arrays. Instead we need to use the exception capability and the resulting valueCount array, which has a somewhat different structure.

Making these replacements is a bit more involved than I can tackle at the moment. I am shooting to get this done on Wednesday or Thursday.

/cc @cncoleman

**Comment by esjewett** [comment]
This change should cut roughly 50% from map rendering time. Will continue to look at other options. I believe we either already had or this introduced an issue with the size calculation and legend labels, so please be aware for now.

**Comment by cncoleman** [comment]
I can drag the brush and the data does update, albeit with a significant lag. Before it did not update at all. I'm still running into problems with the map rendering if it is moved at all.
Here is what I see:
https://www.dropbox.com/s/evx6y4b9i3bo5eh/Screenshot%202015-10-13%2010.56.10.png?dl=0
I loaded an existing .03 project file built yesterday. Could that be the problem?

**Comment by esjewett** [comment]
I doubt the file is the problem. Can you send it to me?

Render-on-move or -zoom with the map does have a delay and it appears to be doing some calculations 2x and therefore taking twice as long as it should, so that's something else for me to look at fixing.

**Comment by cncoleman** [comment]
It's in AHR/Voltaire/Data/minimized-data-set/

**Comment by esjewett** [comment]
It was a bug in the facet filter loading code. Sorry about that. I fixed a couple of things including the issue that was causing the error with this file. I think the error was probably causing the map to not properly re-render after being moved as well. Hopefully it works now.

**Comment by esjewett** [comment]
At this point, most of the performance issues have been dealt with.
