### ISSUE TITLE
Need a progress indicator

### ISSUE THREAD

**Issue by esjewett** [humanitiesplusdesign/palladio#76]
Maybe a circle or something around the "P" that can pulse?

**Comment by cncoleman** [comment]
Can we use css animation rather than animated gif?
Like this: http://www.jasonkenison.com/2014/09/63/Death-of-the-loading-gif

**Comment by esjewett** [comment]
@cncoleman Ah, of course! Completely slipped my mind that this was a possibility.

**Comment by esjewett** [comment]
This update is probably enough to fix this particular issue. Should do more work around promise-ifying the UI and displaying a spinner during Crossfilter operations (dimension/group creation, filtering). Will create a new issue for that.
