### ISSUE TITLE
Google spreadsheets can no longer publish to web as format:csv

### ISSUE THREAD

**Issue by atomrab** [humanitiesplusdesign/palladio#8]
Apparently this functionality, which was necessary to load a Google spreadsheet directly into Palladio, was removed in the latest version, and is not likely to come back. According to [this user forum](https://productforums.google.com/forum/#!topic/docs/An-nZtjaupU), some people have been able to load csv from a Google spreadsheet by changing the "Share" link to /export?format=csv&id or export?format=csv, at least as of last May. But this does not work when trying to load into Palladio at the moment. If there's a fix on the Palladio side, that would be best, since the load-from-sheet function is really convenient; but if not, that tab should probably not offer the option to load from a Google spreadsheet.

I tried loading from a spreadsheet that had been published to the web with the publication link (which ends in html), with a manually edited version that ended in csv, with the normal "anyone can view" sharing link, and with the "anyone can view" sharing link changed to /export as above. All produced the same error message: "Sorry, an error occurred while fetching the data".

**Comment by esjewett** [comment]
Definitely an issue and we do not believe this is possible any more because Google seems to have dropped CORS on the publicly shared spreadsheet links. Dropbox Public folders do support this. In the meantime, we'll have to remove the Google sheets wording from the upload text.
