### ISSUE TITLE
Use case: visualize all connections active during a time range on the basis of existence, rather than start date

### ISSUE THREAD

**Issue by atomrab** [humanitiesplusdesign/palladio#9]
This use case relates to an attempt to visualize connections between ancient Greek cities on the basis of the co-presence of specific coin types. The user therefore wants to create a time range visualization by the period of existence of each coin type (this works), and then filter that range to show which types were being minted within a given period of time. All types have start and end dates. When a time range visualization is constructed and displayed as bars, all types appear with both start and end dates. When a time-range filter is created, however, it only filters by start date (so "all types that start to be minted between 550 and 525). The user's query is "all types that either start, end, or continue to be minted during the time range 550 and 525" (and, conversely, no types that are not being minted during that time range). Is this a functionality that already exists? If not, it would be really useful, and in keeping with the purpose of Priestley's original time-range bar graph ("who is alive at point X?").

**Comment by esjewett** [comment]
I suspect this is already supported, but I may just not understand the question (or maybe that you've found a bug - wouldn't be the first time!). In the timespan filter, there are actually three separate filters that can be applied:

1. Filtering on the top axis filters on dates on the right side of the bars (usually end-dates)
2. Filtering on the bottom axis filters on dates on the left side of the bars (usually start-dates)
3. Filtering in the middle does what I believe you are looking for, filtering down to "active" timespans within the filter. e.g. records that start or end in the filter, or that start before the filter and end after.

Here's a screenshot of this type of filtering with the sample data set.

![screen shot 2015-04-14 at 10 57 52 am](https://cloud.githubusercontent.com/assets/4822/7141129/21c79bf4-e295-11e4-938c-3b87b6ac3020.png)

Is this what you are looking for?

**Comment by atomrab** [comment]
Ethan,
Thanks, as always, for the swift reply -- and yup, that was exactly what we
were trying to do. We hadn't twigged to the fact that the different zones
of the timespan visualization had different filtering actions. This solves
the problem!

In exchange, here is a real bug report: the "select a file" button to
upload a Palladio project isn't working on Firefox 37.0.1. That's not much
of a trade -- you solved my problem and I gave you another one -- but it
seems to be the only currency I deal in...

Thanks again!

Adam

**Comment by esjewett** [comment]
Great - I'm glad that's working. Agreed it's not obvious that there are 3 different filters in the timespan. We tried a few things to make that clearer and they didn't help, but we need to try more! I've opened a new issue for the FF problem. At the moment we're only really testing in Chrome, but we'd like this to work in FF and Safari as well, at the least, so issue reports are very helpful.
