### ISSUE TITLE
SVG download fails in Map view

### ISSUE THREAD

**Issue by cncoleman** [humanitiesplusdesign/palladio#90]
Looking at Simplified Voltaire Letters + Places. No error. Just SVG download fail. 
(Console also shows a number of imgs failing to load)
![screen shot 2015-10-22 at 2 35 50 pm](https://cloud.githubusercontent.com/assets/288005/10678937/3b9fa122-78ca-11e5-9141-84fc3ca0e8a9.png)

**Comment by esjewett** [comment]
This should now be fixed in master on on tag 1.1.2, which has been deployed to the main site.
