### ISSUE TITLE
Vectors not appearing in graph component

### ISSUE THREAD

**Issue by cncoleman** [humanitiesplusdesign/palladio#97]
see endangered languages visualization/three.html

**Comment by esjewett** [comment]
This should be fixed with https://github.com/humanitiesplusdesign/endangeredlanguages/commit/61c411c7d869aa26c464c649e6f62c9ce18d2b67  I'll also try to apply the fix to the main Palladio repository so this won't happen to people in the future.

**Comment by cncoleman** [comment]
@esjewett I'm still seeing this in the ahr components

**Comment by esjewett** [comment]
AHR still had the old version of Palladio. I updated at pushed a new commit. Can you try now?
